---
# tasks file for tamay.httpd

- name: "Install httpd and mod_ssl"
  package:
    state: present
    name:
      - httpd
      - mod_ssl

- name: "Install additional httpd modules"
  package:
    state: present
    name: "{{ httpd_modules }}"

- name: "Enable mpm_{{ httpd_mpm_module }}_module"
  template:
    src: 00-mpm.conf.j2
    dest: /etc/httpd/conf.modules.d/00-mpm.conf
    owner: root
    group: root
    mode: 0644
  notify: restart_httpd

- name: "Disable welcome.conf"
  replace:
    path: /etc/httpd/conf.d/welcome.conf
    regexp: '^((?!#))'
    replace: '#'
  notify: reload_httpd
  when: httpd_disable_welcome | bool

- name: "Copy /etc/httpd/conf.d/ssl.conf"
  template:
    src: ssl.conf.j2
    dest: /etc/httpd/conf.d/ssl.conf
    owner: root
    group: root
    mode: 0644
  notify: reload_httpd

- name: "Copy vhosts to /etc/httpd/conf.d"
  template:
    src: vhost.j2
    dest: /etc/httpd/conf.d/{{ item.servername }}.conf
    owner: root
    group: root
    mode: 0644
  notify: reload_httpd
  loop: "{{ httpd_vhosts }}"

- name: "Copy ssl-vhosts to /etc/httpd/conf.d"
  template:
    src: vhost-ssl.j2
    dest: /etc/httpd/conf.d/{{ item.servername }}-ssl.conf
    owner: root
    group: root
    mode: 0644
  notify: reload_httpd
  loop: "{{ httpd_vhosts_ssl }}"

- name: "Create /var/www/vhosts"
  file:
    state: directory
    path: /var/www/vhosts
    owner: root
    group: root
    mode: 0755

- name: "Start and enable httpd service"
  service:
    name: httpd
    state: started
    enabled: yes
