---
# handlers file for tamay.httpd

- name: "Reload httpd"
  service:
    name: httpd
    state: reloaded
  listen: reload_httpd

- name: "Restart httpd"
  service:
    name: httpd
    state: restarted
  listen: restart_httpd
